### ISSUE TITLE
BungeeCord fallbacks

### ISSUE THREAD

**Issue by juliarn** [CloudNetService/CloudNet#17]
When having this fallback configuration for example:
```json
"bungeeFallbackConfigurations": [
  {
	"targetGroup": "Proxy",
	"defaultFallbackTask": "Lobby",
	"fallbacks": [
	  {
		"priority": 1,
		"task": "Lobby",
		"permission": null
	  },
	  {
		"priority": 1,
		"task": "TestServer",
		"permission": null
	  }
	]
  }
]
```
A player is still only able to connect if a service of the "defaultFallbackTask" is available, so "Lobby". If there is no Lobby online, but an instance of "TestServer", the bungeecord says there is no fallback server available, although the "TestServer" task is defined as a fallback.

**Comment by realPanamo** [comment]
The issues seems to be here: https://github.com/CloudNetService/CloudNet-v3/blob/007d96d45a47a86f6914ad276296854e3c0146ab/cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/bungee/BungeeCloudNetHelper.java#L127-L131

It looks like the getFilteredEntries() method does return null, so "server" isn't being assigned.
This leads the cloud to look for the availability of the defaultTask.
