### ISSUE TITLE
PocketMine-MP

### ISSUE THREAD

**Issue by HowToPeaZYT** [CloudNetService/CloudNet#183]
Please add PocketMine-MP Support to CloudNET :/

**Comment by McRuben** [comment]
PocketMine is written in PHP, CloudNet is written in Java, I don't think it would be easy to add this, so we won't add it. But if someone wants to add support for it, we won't do anything against it.

**Comment by NxtUser-HD** [comment]
´Waterdog is an fork of BungeeCord and works fine with PocketMine-MP :o

**Comment by NxtUser-HD** [comment]
So I think that you can make CloudNET compatible with PocketMine somehow

**Comment by McRuben** [comment]
The problem is not the compatibility with the Proxy, the problem is, that it's not written in Java.

**Comment by McRuben** [comment]
If someone would make a java wrapper for the PHP system, this might work

**Comment by McRuben** [comment]
And also, why should we implement PocketMine? Nukkit works fine with WaterFall

**Comment by NxtUser-HD** [comment]
because i can't java. I am PHP Dev 😂

**Comment by McRuben** [comment]
I don't think that this work would be worth it for 1 or maybe 2 users that I've seen here.

**Comment by realPanamo** [comment]
I agree, it's not really worth it.

**Comment by xxAROX** [comment]
IDK how CloudNet sends data between downstream-servers but here is a Repo [Alemiz112/StarGate](https://github.com/Alemiz112/StarGate), it uses socket communication.

* This is a hint
